# Generated by Django 2.1.5 on 2019-01-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='title'),
            preserve_default=False,
        ),
    ]
